DROP TABLE IF EXISTS "person";

CREATE TABLE "person" (
  id SERIAL PRIMARY KEY,
  name varchar(255) default NULL,
  age integer NULL
);

INSERT INTO person (name,age)
VALUES
  ('Giselle Shaffer',79),
  ('Naida Byers',60),
  ('Ferdinand Quinn',76),
  ('Shelly Marquez',68),
  ('Veronica Deleon',35),
  ('Echo Solis',61),
  ('Beau Cantu',21),
  ('Todd Walker',53),
  ('Guy Neal',88),
  ('Carly Villarreal',17),
  ('Conan Sellers',60),
  ('Vladimir Travis',91),
  ('Aquila Santiago',43),
  ('Connor Arnold',66),
  ('Zenaida Hill',14),
  ('Imani Stanton',20),
  ('Rana Skinner',36),
  ('Zorita French',66),
  ('Edan Paul',16),
  ('Calista Fischer',24);
INSERT INTO person (name,age)
VALUES
  ('Reed Nielsen',26),
  ('Macaulay Poole',66),
  ('Lucian Wilder',44),
  ('Deirdre Kemp',73),
  ('Vera Blevins',94),
  ('Rajah Norman',68),
  ('Octavius Carlson',0),
  ('Macon Shepherd',46),
  ('Aaron Farmer',18),
  ('Lacota Daniel',31),
  ('Martha Mclean',81),
  ('Delilah Mccarty',29),
  ('Willow Clemons',65),
  ('Lisandra Hayden',43),
  ('Mercedes West',49),
  ('Amos Gutierrez',55),
  ('Ella Blair',98),
  ('Pearl Sanford',76),
  ('Theodore Phillips',82),
  ('Quyn Franco',7);
INSERT INTO person (name,age)
VALUES
  ('Dominique Ballard',77),
  ('Christen Goff',40),
  ('Carla Evans',88),
  ('Gage Holder',93),
  ('Charissa Larson',16),
  ('Xena Harris',98),
  ('Inez Charles',48),
  ('Walker Daugherty',82),
  ('Yeo Calhoun',2),
  ('Drake Charles',77);
INSERT INTO person (name,age)
VALUES
  ('Simone Farmer',99),
  ('Paul Huffman',81),
  ('Alfreda Boyer',49),
  ('Eve Mcneil',33),
  ('Mason Mccall',1),
  ('Xander Harper',82),
  ('Sarah Evans',24),
  ('Beck Mullins',39),
  ('Branden Anthony',56),
  ('Mason Mcgowan',36),
  ('Whitney Forbes',40),
  ('Holmes Reeves',43),
  ('Devin Mcfadden',80),
  ('Jerry Callahan',14),
  ('Kim Campos',57),
  ('Gemma Peterson',68),
  ('Mariko Patel',59),
  ('Lee Whitaker',25),
  ('Margaret Perez',30),
  ('Alexa Walker',33);
INSERT INTO person (name,age)
VALUES
  ('Stephanie Jacobs',37),
  ('Grady Morrison',12),
  ('Mariam Osborne',42),
  ('Ezra Cole',94),
  ('Shelley Berry',33),
  ('Cally Campos',83),
  ('Micah Harrison',80),
  ('Britanni Mclaughlin',80),
  ('Laurel Rich',79),
  ('Alfreda Vaughn',41),
  ('Cherokee Saunders',21),
  ('Josiah Kirby',31),
  ('Suki Myers',49),
  ('Ifeoma Mathis',86),
  ('Sopoline Hudson',17),
  ('Kelsey Delacruz',54),
  ('Lewis Dawson',45),
  ('Tara Mclaughlin',74),
  ('Giacomo Morin',36),
  ('Sebastian Hays',56);
INSERT INTO person (name,age)
VALUES
  ('Wyoming Ellison',55),
  ('Cullen Lester',92),
  ('Cyrus Wilson',79),
  ('August Todd',56),
  ('Philip Tillman',63),
  ('Burke Little',78),
  ('Walker Holt',33),
  ('Cally Cunningham',6),
  ('Murphy Wilcox',83),
  ('Paloma Mooney',16);
INSERT INTO person (name,age)
VALUES
  ('Lawrence Cannon',35),
  ('Jeremy Cole',59),
  ('Oleg Cantrell',85),
  ('September Stout',14),
  ('Cassandra Cantu',20),
  ('Eleanor Howell',93),
  ('Vielka Rogers',73),
  ('Eaton Fulton',30),
  ('Kato Gay',91),
  ('Vanna Daugherty',96),
  ('Melodie Head',95),
  ('Asher Evans',89),
  ('Melissa Strong',34),
  ('Lana Lamb',14),
  ('Amena Mayer',96),
  ('Plato Cooper',14),
  ('Zenia Garner',50),
  ('Jonah Glenn',40),
  ('Mufutau Holcomb',54),
  ('Castor Johnson',22);
INSERT INTO person (name,age)
VALUES
  ('Harrison Workman',45),
  ('Emi Weeks',46),
  ('Jolie Rutledge',48),
  ('Stephen Watkins',81),
  ('Martina Garza',43),
  ('Ginger Barry',20),
  ('Paul Cohen',73),
  ('Fallon Glenn',8),
  ('Felix Whitfield',91),
  ('Damian Frank',61),
  ('Chase Pollard',69),
  ('Dieter Gilliam',87),
  ('Jakeem Bird',41),
  ('Ignatius Simmons',65),
  ('Olga Harmon',24),
  ('Fulton Boyle',19),
  ('Abdul Bullock',98),
  ('Brianna Pierce',5),
  ('Gemma Vega',20),
  ('Colin Levy',82);
INSERT INTO person (name,age)
VALUES
  ('Mira Lee',16),
  ('Hannah Monroe',90),
  ('Dennis Ball',89),
  ('Yael Hooper',43),
  ('Hyatt Austin',97),
  ('Barclay Strong',36),
  ('Yuri Greer',31),
  ('Olga Lester',14),
  ('Alea Reed',88),
  ('Lavinia Singleton',44);
INSERT INTO person (name,age)
VALUES
  ('Mason Shields',13),
  ('Melodie Ramsey',14),
  ('Simone Floyd',37),
  ('Leo Preston',30),
  ('Kirestin Figueroa',75),
  ('Pearl Burns',15),
  ('Jermaine Contreras',48),
  ('Chaim Melendez',44),
  ('Cameron Conner',27),
  ('Shoshana Fields',73),
  ('Damian Bass',9),
  ('Oleg Holden',100),
  ('Aquila Horton',70),
  ('Aidan Salazar',51),
  ('Ima Goff',58),
  ('Giacomo Palmer',9),
  ('Quin Rowland',33),
  ('Judah Chambers',78),
  ('Wylie Holland',40),
  ('Dana Harrell',63);
INSERT INTO person (name,age)
VALUES
  ('Alan Banks',45),
  ('Ivy Levine',96),
  ('Trevor Randall',32),
  ('Armando Melton',15),
  ('Maxine Mejia',49),
  ('Jennifer Buchanan',78),
  ('Kimberley Harper',43),
  ('Macy Flowers',70),
  ('Brendan Palmer',2),
  ('Hamish Head',42),
  ('Danielle England',13),
  ('Orli Ford',39),
  ('Brenna Hampton',48),
  ('Yetta Wilkerson',30),
  ('Cecilia Lawrence',72),
  ('Anjolie Gallegos',33),
  ('Leonard Espinoza',24),
  ('Oren Alston',10),
  ('Shana Pollard',52),
  ('Benedict Schwartz',12);
INSERT INTO person (name,age)
VALUES
  ('Brennan Berger',56),
  ('Maris Reed',75),
  ('Camille Key',76),
  ('Hashim Espinoza',51),
  ('Belle Melton',14),
  ('Leo Mann',50),
  ('Regina Trevino',12),
  ('Shaine Bean',85),
  ('Tyler Sparks',41),
  ('Fulton Branch',65);
